[[ProtocolBuffersCompiler]]
arch = "aarch64"
git-tree-sha1 = "c608c86140090fb4a30ecede6bd35f6ddc8325ae"
os = "macos"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "206a62d0919ce7c747ec55753638b2ba98f6f94ca607215a7ab1c52a24cdfb38"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.aarch64-apple-darwin.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29670e9725477d149f503913c0410ce61eca4939"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "a3426cfecf4ba27b09335b5ccc64d19808a68c5d957fc4098547f21b9767d4b5"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73ff51b1a88d486df5285e5696390cbe613b6cc5"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "f1d8b7f47f7a103c569e402b9e6d2bc82480e93e413fc68d2aa20a17763ee159"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.aarch64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "aarch64"
git-tree-sha1 = "215678f51e1a4ecdb3c87e4b82e2e8b6945e6140"
os = "freebsd"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "5cca8f1cce4d72906d3eb5e45d784df9fb0d30605346fb28f5b8fa519d402bcf"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.aarch64-unknown-freebsd.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0195c080fbd9d6db083d382d40e8616e87841e2"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "a8f2bbd451ae12c4eae892f15d856a5a8453c6564ff64d48459b2d8c8ceb444a"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "183c264931a523dbde5ea5d499bd84298cc8ba04"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "e32bbc93d589f432589bf952593d8e18ddea2c1a876e80abba9d1dfa513b32da"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2d8a73ec099786eb9e160f84b6c3f4fba235539"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "c743b2e4da513567107bee74fc6dacc373b63fcdca71cca7bbfb97693e9a9c35"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f936ca14f7b252f9e049faf930ff3a501a7dca90"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "90d2e4cf862325bd2491727f93082c8f0227e985bac0c4751f7b87cd753a62c9"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77fac4e17d005a51a094e1b40e345d8ed28a5b6a"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "a13b28eb3db78bfc8ab9a413167ae2c0b70857df9d8a899d4a8a28a09f8948c9"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.i686-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51de34cd29f9f0e640708dfd002586a784f929ac"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "fcb02bb907b720e059984708939e009c3e4aff2da64e0901442672c3925d28bf"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.i686-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "472c6b4fb6674a2604ff60351b760f93928d8c53"
os = "windows"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "78868468ec4310e8e3747b9e0086f68d231929f109d3f105cf03c1e2fa6b1bdc"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.i686-w64-mingw32-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42f1343b377bacd54e955c2c8c83609928800385"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "36609b16d8f1b3988337c422033b44a25181acd0f6426cd48426f6eecf6b14e7"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb330216a1f1e35862881247580ae55f4472b5c0"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "39153ab7895896d0c063b77c35c5e0a89f008aa360349a94e62937285c838bd6"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.riscv64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
git-tree-sha1 = "004b166ef5da27a0f9196da74d3ab3fd14dd55b5"
os = "macos"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "ddad37970ee0a970ebd1f7845a056aedebcfee13714c91c14efe935eaf5ed2e1"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.x86_64-apple-darwin.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b770c46ac6ecf47e817bfa89e7aaa4a03c1758e"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "601750513f4b606d61200658879a7f6aed4a1338894615b2ef2adb0a433b7b22"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d5176604621e76d713409c435ce1f8bec9431c1"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "c06f6126acd7eb1419954df3cd0488c34e15bf8d9c832f1b02995f7063567804"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.x86_64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
git-tree-sha1 = "dcb717e2fac43b68883a12673c98a1133988de8c"
os = "freebsd"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "c31baf3b5cdc91e5a5531a46f23013950319035833bb0cd4f426807c73977cef"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.x86_64-unknown-freebsd.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "888ba3b2a405f6cc78853991ca668d0766e1ec01"
os = "windows"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "c2b5db118a61c94400bf0500ee6d7df81d4e31ca35225ca5fe7b0929b82696f2"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.1+0/ProtocolBuffersCompiler.v3.16.1.x86_64-w64-mingw32-cxx11.tar.gz"
