[[ProtocolBuffersCompiler]]
arch = "aarch64"
git-tree-sha1 = "bd86b3605fc74432aff8f63c80cb8c81d3ca8412"
os = "macos"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "10f1b49ccf34515363fb746d8f10ea03d8b01df33ab7389c60f4d950d90d0017"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.aarch64-apple-darwin.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c25dbd10ed1fe291310ab2ad29770c391c67c1e0"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "4dde7354ff601bd553d4c41fb7d3ed6263c3c6b24942092cfab147cdc34ddd08"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "676e00812b91a61677d2fae269ec4cb1aa0b2246"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "4796c535f2d802e3db5cf50c8710f69b0a522414937f7e8dfcefac97c93f8a1e"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.aarch64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "aarch64"
git-tree-sha1 = "380d076a50cac079bfcf6f73de3214ac3cb6a786"
os = "freebsd"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "9050b84fef46b8a09bda0748cc70ba4372da5e25eb901ab91818cbe797a3b2dc"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.aarch64-unknown-freebsd.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd2c5300fee2ff262dc0699eb3a6c69e762e1088"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "93aa3ddccc7a8f9e668a02ef29c44b025a4b98e2461ba0a5bbada5b31ad9fa71"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54a7a529680f01bb874b3810116391036282ccc4"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "8b5de856273c1a6d4add58d5aead6e816ab6f3380771f75bf5d3c87d6ba7db9d"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65efed9129ad23997b16636ecf0f1545c1c73a83"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "13f4a049c05b858900f011cba0cb0cd6821d4d0205a82b411dbf2336d54d03fb"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86afbd6b66c47c0618b2ccaefe4329d8d61b13f7"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "7ecffcbfc25728189b2e6e0ee4aed3305b75ce10e850ae40a9c4d24b63d2477d"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cbefbda737faba2c43e7bfd423d05e09fd883eb"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "82fdf51d0daf38802d57f5e920b4c842603ba1a859e1515e834b1359d338742b"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.i686-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b052e846fa9005748897af84e6d39ceda9f1fd51"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "6feba472736465f01ec6e6157620db79abbcecacbecc69196857b6f0345b148b"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.i686-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4797aeb1387a5135644ce07e34a6e6f6e752a0d0"
os = "windows"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "ef6a69757d2ec80c04cd15c7fd8b08ff58cd03988f15f4fd0b18b22eb57ff53a"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.i686-w64-mingw32-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2deb7648b0c7ee2e9a793b2c0174a7baa3b712a1"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "abd857a81ca4388a98dfaf15408df1048441166809c17f56fedd762e8bd97efc"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e34c8967b99f91ba1464f2646188a3e7657f7db5"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "90d07ce91dc9a713209536baf53fcb3501224ecca44d2455a0edab69f5b8fe4a"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.riscv64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
git-tree-sha1 = "d685fa89595e89ec37cba63abfeb503ff468e41c"
os = "macos"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "8cd3464d9946daf86c4f7c15dcf99c34cbdb978b86b706cc1ea56b040f8ba237"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.x86_64-apple-darwin.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "056cfb9a37bbcdf7720c156311feed1474f4afe3"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "429ed4ef58efe28f953e3b243e369a093592390b67d055508be9e6e40b20e83a"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d8af334e015be4813efa680246c69fee0a12cd7"
libc = "musl"
os = "linux"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "b2f33d7c721b0f3990b980763deac410473d37967a361ab7f368590cf4ac3426"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.x86_64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
git-tree-sha1 = "f8eb9e92ea6584f553c765acd46c7b5271b28aca"
os = "freebsd"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "2a45cb12a565ff6001abe3848ef49c3d949034ba405062da1738d3ae913c6e79"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.x86_64-unknown-freebsd.tar.gz"
[[ProtocolBuffersCompiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bae06c95c493a0933f34f6dd2e97d83d07afac3"
os = "windows"

    [[ProtocolBuffersCompiler.download]]
    sha256 = "6ccafa9e4a337d3d61a4b631905447c62840faf33600ccee9c465582864f0e59"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersCompiler_jll.jl/releases/download/ProtocolBuffersCompiler-v3.16.0+0/ProtocolBuffersCompiler.v3.16.0.x86_64-w64-mingw32-cxx11.tar.gz"
